### ISSUE TITLE
Suggested shortcut for `regional_mom6`

### ISSUE THREAD

**Issue by navidcy** [COSIMA/regional-mom6#101]
At the moment the examples in the notebooks suggest this shortcut for the package

```python
import regional_mom6 as rm
```

But `rm` is very very similar to the unix command to delete files/directories. This could be confusing? For example I get a bit scared when I see methods emanating from `rm`. Should we suggest something else, e.g.,

```python
import regional_mom6 as rmom6
```
?

**Comment by ashjbarnes** [comment]
Yeah `rmom6` is nice! perhaps we tack this onto PR #99 ?

**Comment by navidcy** [comment]
Deal
