### ISSUE TITLE
Question regarding `ep2ap` and `ap2ep`

### ISSUE THREAD

**Issue by navidcy** [COSIMA/regional-mom6#102]
Are these functions from a different python package? If so we should just import them from there.

https://github.com/COSIMA/regional-mom6/blob/3e9844286db015e17940bbbacc2c35f7ddc82e23/regional_mom6/regional_mom6.py#L36-L153

**Comment by navidcy** [comment]
If we are keeping them, can we rename them to something meaningful that is self-explanatory?

**Comment by ashjbarnes** [comment]
Yeah agreed. These are needed for adding tides which isn't finished yet! I'll do a big "add tides" pr at some point and tidy these docstrings along the way

**Comment by navidcy** [comment]
I'm closing this for now since we nuked these methods until full tide forcing is supported.
