### ISSUE TITLE
Proper/better way to tag new releases?

### ISSUE THREAD

**Issue by navidcy** [COSIMA/regional-mom6#110]
I'm wondering what's the proper way to automate the procedure of tagging a new release? I know how to do this for a Julia package but not with a python package.

I'm asking whether there is a way that with a simple action we get, e.g., the following:
- a new tag
- a new GitHub release
- the `pyproject.toml` or other `.toml` and related files are updated
- conda knows about the latest version of the package
- and the docs populate a new version

At the moment, tagged versions of the package don't have their own doc version -- only the docs of the "latest" is available; see screenshot below

<img width="980" alt="Screenshot 2024-02-22 at 13 32 56" src="https://github.com/COSIMA/regional-mom6/assets/7112768/9315234c-197a-42d7-88b1-041f1d1e3471">

cc @angus-g

**Comment by aekiss** [comment]
FYI @aidanheerdegen's model release team at NRI are setting up CI test-based automated tagging, with the major version updated only if test results change, otherwise minor version is updated

**Comment by aidanheerdegen** [comment]
Thanks for the shoutout @aekiss but I think what @navidcy is asking about is the machinery to get this working seamlessly.

If you want an example @dougieaquire recently update the `payu` publishing machinery using `pyproject.toml` and `versioneer`.

https://github.com/payu-org/payu/pull/403

It also publishes to `conda` and `pypi`.

**Comment by navidcy** [comment]
Yeap, I was thinking more something like in the spirit of what @aidanheerdegen points out! Thanks!

**Comment by navidcy** [comment]
Would a GitHub action, e.g., like https://github.com/xgcm/xgcm/blob/master/.github/workflows/pythonpublish.yaml streamline the procedure?

**Comment by dougiesquire** [comment]
@navidcy there is a bot ([regro-cf-autotick-bot](https://github.com/regro-cf-autotick-bot)) that should automatically create PRs for version updates when the PyPI distribution is updated - see [here](https://conda-forge.org/docs/maintainer/updating_pkgs/#pushing-to-regro-cf-autotick-bot-branch) for details. Version 0.2.1 is [the latest version on PyPI](https://pypi.org/project/regional-mom6/), which is why conda-forge is the same.

So the process for updating should usually involve only two steps:
- upload a new version to PyPI
- accept the automatically generated pull request in the [conda-forge feedstock repo](https://github.com/conda-forge/regional-mom6-feedstock)

If it's helpful, I can set up a github workflow to automatically upload new releases to PyPI?

**Comment by navidcy** [comment]
Yes please, @dougiesquire that would be great help!

**Comment by navidcy** [comment]
Hm... I went through the resources you pointed out @dougiesquire and couldn't find an example of a GitHub action.

But after some PRs are merged, I'm gonna tag a new release v0.5.0. How do I update the pypi (and by consequence the conda-forge) when the new release is tagged? I'm just asking how to do it manually, and we'll let the automation and GitHub action for later. (I'd like @dsroberts to install the v0.5.0 in the conda-analysis 24.01 environment on NCI, that's why I'm asking.)

**Comment by angus-g** [comment]
The pypi package is under my account, so I can do that manually once the tag is up, and then we can bump the conda version (which should be easier now that we have maintenance over it, I think?)

**Comment by dougiesquire** [comment]
> and then we can bump the conda version (which should be easier now that we have maintenance over it, I think?)

Yup, a PR should be opened automatically in the feedstock repo

**Comment by navidcy** [comment]
Great! I'll ping you @angus-g when I tag the new release. Thanks both!

**Comment by navidcy** [comment]
@angus-g can you push [v0.5.0](https://github.com/COSIMA/regional-mom6/releases/tag/v0.5.0) to pypi?

**Comment by navidcy** [comment]
@angus-g can you add me as maintener on pypi? I just made an account; username `navidcy`

**Comment by navidcy** [comment]
@dougiesquire [pypi v0.5.0](https://pypi.org/project/regional-mom6/) but I don't see any automatic [PR generated](https://github.com/conda-forge/staged-recipes/pulls). Am I looking at the right spot?

**Comment by navidcy** [comment]
oh... is it here that the PR will appear?
https://github.com/conda-forge/regional-mom6-feedstock/pulls

**Comment by angus-g** [comment]
> oh... is it here that the PR will appear? https://github.com/conda-forge/regional-mom6-feedstock/pulls

Yes. I don't have a sense for how long the bot takes to get around to the updates, could just take a moment...

**Comment by navidcy** [comment]
OK, I'll give it a day or so :)

**Comment by navidcy** [comment]
> If it's helpful, I can set up a github workflow to automatically upload new releases to PyPI?

@dougiesquire I'll leave this on you, right? It will be very helpful! now both me and @angus-g are maintenairs in the pypi entry of this package (I don't know if that's a useful piece of info for the GitHub action)
