### ISSUE TITLE
`deepness`

### ISSUE THREAD

**Issue by navidcy** [COSIMA/regional-mom6#114]
Is `deepness` the property/variable name that MOM6 expects or is it an ad-hoc choice here?

https://github.com/COSIMA/regional-mom6/blob/b0e13c5f6a45eec9451ea2165f19ae0fe9176aed/tests/test_expt_class.py#L158

**Comment by ashjbarnes** [comment]
I choses silly names for my dimensions in the tests to ensure that the dictionary mapping of random names onto mom6 ones would work. Hence `lona` `lata` but these were sadly less creative

**Comment by navidcy** [comment]
oh I thought that `lona` and `lata` were referring to A-grid or something...

a comment might be useful here then
