### ISSUE TITLE
`motu_requests` docstring does not describe `buffer`

### ISSUE THREAD

**Issue by navidcy** [COSIMA/regional-mom6#120]
We should add a short description of what `buffer` is.

https://github.com/COSIMA/regional-mom6/blob/b0e13c5f6a45eec9451ea2165f19ae0fe9176aed/regional_mom6/regional_mom6.py#L272

**Comment by ashjbarnes** [comment]
The Motu Requests function is sadly deprecated anyway. I've been lazy and left it in the repo hoping that whenever Copernicus finishes their new API we can salvage it. Their new API is in Beta state and in my experience (as of Jan anyway) is that it's still a bit unreliable and under construction. In the meantime should we remove this function entirely and just dig through the git history when we want to reference the code?
