### ISSUE TITLE
Is `buffer` implicitly assumed to be an `int`?

### ISSUE THREAD

**Issue by navidcy** [COSIMA/regional-mom6#121]
Here,

https://github.com/COSIMA/regional-mom6/blob/b0e13c5f6a45eec9451ea2165f19ae0fe9176aed/regional_mom6/regional_mom6.py#L245-L247

`buffer` is treated as integer. But from the description of what `buffer` is that I find in the comments, `buffer` could be a float and then this line will error, right?

**Comment by navidcy** [comment]
(If we need to modify this, let's do it in #112.)

**Comment by ashjbarnes** [comment]
Buffer is an integer number of grid points to take either side of the slice. So the total extra number of points added is buffer * 2. The buffer is required for interpolation with xesmf later on. I didn't really test different buffer sizes, so we could increase the default beyond two with minimal performance impact if we're worried it's too stingy!

**Comment by navidcy** [comment]
Gotcha.

My confusion stemmed that elsewhere `buffer` was a float, e.g.,

https://github.com/COSIMA/regional-mom6/blob/7ea047786954314721095aa58183b7b73e4b6f5e/regional_mom6/regional_mom6.py#L272

But I see you. OK then, we should clarify here:

https://github.com/COSIMA/regional-mom6/blob/7ea047786954314721095aa58183b7b73e4b6f5e/regional_mom6/regional_mom6.py#L181-L182

that `buffer` is an integer denoting the number of buffer grid points. 

Also we should include `buffer` in the list of `Args` at

https://github.com/COSIMA/regional-mom6/blob/7ea047786954314721095aa58183b7b73e4b6f5e/regional_mom6/regional_mom6.py#L187

**Comment by ashjbarnes** [comment]
Buffer has been removed
