### ISSUE TITLE
Load input using `cosima_cookbook`

### ISSUE THREAD

**Issue by navidcy** [COSIMA/regional-mom6#131]
I'm trying to load input using `cosima_cookbook` instead of `xarray` in the ACCESS-OM2 forced example and I get an error. I must be doing something silly. Can somebody help?

https://gist.github.com/navidcy/7303d52935ced4253f9eb62b3080459c

cc @angus-g

**Comment by angus-g** [comment]
Yeah, you're asking for a time range around 2003, but that dataset (and the data you manually queried) is in like the 2070s somewhere.

**Comment by navidcy** [comment]
Great. Thanks. We shouldn’t use an ryf exp now that zi’m thinking about it.

**Comment by navidcy** [comment]
I'm closing this since it's not relevant anymore. But note, this is relevant for the https://github.com/COSIMA/cosima-recipes/pull/338
We'd need to use the cookbook to load the data in the ACCESS-OM2 example before merging in cosima-recipes
