### ISSUE TITLE
Remove tide-related methods until tides are actually supported

### ISSUE THREAD

**Issue by navidcy** [COSIMA/regional-mom6#138]
@ashjbarnes 

If I understand correctly, these methods

https://github.com/COSIMA/regional-mom6/blob/a364cec870b59547a58aa28ebf3eadc56a99bfe2/regional_mom6/regional_mom6.py#L30-L153

are neither used nor tested at the moment. They are just there in anticipation of tide forcing functionality. Or are they used?

If they are not used could we remove them and add them back together with the tide-forcing functionality? What do you think?

(If this will complicate or break any workflows you've set up for research then let's not bother -- feel free to close the issue in that case.)

**Comment by ashjbarnes** [comment]
yeah this is fine we can take them out! I'll they exist in the tides branch anyway
