### ISSUE TITLE
Need to provide `TOPO_FILE` arg in `MOM_input` otherwise MOM6 looks for bathymetry in `topog.nc`

### ISSUE THREAD

**Issue by AVEllepola** [COSIMA/regional-mom6#172]
I am currently using regional_mom6 version 0.5.1. I get the following error when I try to run the reanalysis example. Renaming a copy of the `bathymetry.nc` file in the inputdir as `topog.nc` resolved this. Just wanted to share this as a user experience. 
![Untitled](https://github.com/COSIMA/regional-mom6/assets/117201968/bb6c2c55-21bf-46a5-a97e-b96a9010c7c3)

**Comment by navidcy** [comment]
thanks @AVEllepola! I just renamed the issue title to be descriptive of the situation.

cc @ashjbarnes

**Comment by navidcy** [comment]
I'm wondering if the expectation for a bathymetry file called `topog.nc` comes from MOM6 itself or from the MOM6 input files that the regional-mom6 package provides. @ashjbarnes do you have an idea?

**Comment by navidcy** [comment]
Here it seems that the "premade" input files are such that topography is expected to be read from file:

https://github.com/COSIMA/regional-mom6/blob/e16340de202cdf87d921d44a27253ccdc0af46e1/demos/premade_run_directories/common_files/MOM_input#L48-L51

But do we provide the `TOPO_FILE` variable?

**Comment by navidcy** [comment]
seems to me that if we don't provide `TOPO_FILE` then MOM6 assumes that the filename is `topog.nc`

https://github.com/NOAA-GFDL/MOM6/blob/b98acd861d835c0bf5894f872516d2338a4791f4/src/initialization/MOM_shared_initialization.F90#L156-L158

**Comment by navidcy** [comment]
@ashjbarnes, what's a good solution here you think?

**Comment by ashjbarnes** [comment]
Thanks @AVEllepola ! This should sort it out. I've tested with this branch and mom6 runs on the example demo again
