### ISSUE TITLE
Iterate through boundaries as part of `expt.initial_condition` method

### ISSUE THREAD

**Issue by navidcy** [COSIMA/regional-mom6#174]
Currently the [demo](https://regional-mom6.readthedocs.io/en/latest/demo_notebooks/reanalysis-forced.html#Step-5:-Handle-the-ocean-forcing---where-the-magic-happens) has

```python
# Set up the initial condition
expt.initial_condition(
    glorys_path / "ic_unprocessed.nc", # directory where the unprocessed initial condition is stored, as defined earlier
    ocean_varnames,
    arakawa_grid="A"
    )

# Now iterate through our four boundaries
for i, orientation in enumerate(["south", "north", "west", "east"]):
    expt.rectangular_boundary(
        glorys_path / (orientation + "_unprocessed.nc"),
        ocean_varnames,
        orientation,    # Needs to know the cardinal direction of the boundary
        i + 1,          # Just a number to identify the boundary. Indexes from 1
        arakawa_grid="A"
        )
```

Given that most times most users will want to create all 4 boundaries, I am wondering if we can make the `for i, orientation in enumerate(["south", "north", "west", "east"])` loop part of the `expt.initial_condition` method. Perhaps we can have a default kwarg which will be `["south", "north", "west", "east"]` and if the user wants to only do one of the boundaries they can provide a different value for the kwarg?

Something like that will simplify the demo.

**Comment by ashjbarnes** [comment]
This is how things used to be actually but I changed it to make things more flexible. See #94

**Comment by ashjbarnes** [comment]
I agree that it would make the IC easier to parse though! Maybe there's a middle ground. I decided to split them because I also thought that adding too many kwargs and options enabling "IC with boundary" or "boundary without IC" would be confusing too

**Comment by navidcy** [comment]
> I agree that it would make the IC easier to parse though! Maybe there's a middle ground. I decided to split them because I also thought that adding too many kwargs and options enabling "IC with boundary" or "boundary without IC" would be confusing too

A kwarg with default would not required to be provided. Users would only provide it if they need something else other than the default.

**Comment by navidcy** [comment]
As is now it’s a bit cumbersome.

**Comment by ashjbarnes** [comment]
@angus-g what do you think? I think this PR #94 we'd chatted about over coffee but discussion didn't make it to github

**Comment by angus-g** [comment]
> Perhaps we can have a default kwarg which will be ["south", "north", "west", "east"] and if the user wants to only do one of the boundaries they can provide a different value for the kwarg?

I think this is probably a reasonable way to go, and at least this removes two positional parameters: orientation, and boundary ID (which I'm not a fan of anyway). I suppose there are not many use-cases where generating individual boundaries is useful.
