### ISSUE TITLE
Set up bathymetry step doesn't work for large regions

### ISSUE THREAD

**Issue by adele-morrison** [COSIMA/regional-mom6#30]
I tried to run the code for a Panantarctic domain:
`yextent = [-90,-37] ## latitude`
`xextent = [-180,180] ## longitude`
using a full node on the normalbw queue.

It crashed with this error:
<img width="1172" alt="Screen Shot 2023-06-06 at 12 29 33 pm" src="https://github.com/COSIMA/mom6-regional-scripts/assets/8506963/d48aa6dc-bfc6-4480-bdd3-e64f2a44d543">

**Comment by navidcy** [comment]
Is this related or duplicate to #18?

**Comment by ashjbarnes** [comment]
This is separate - needs looking into as Adele would have used my new python / ESMF version

**Comment by navidcy** [comment]
Hm... I'm bit confused with how the deps versions work here. Why would e.g. Adele would have used a different version than other users? (This hints that things are not reproducible?)

**Comment by ashjbarnes** [comment]
Yeah sorry that was confusing: issue 18 was raised when bathy was dealt with by single core FRE tools meaning that notebook out of the box could only deal with tiny domains. Adele ran into this issue when using the new implementation which uses ESMF. These issues are therefore unrelated

**Comment by ashjbarnes** [comment]
This has been fixed with the updated xESMF package. Now we can regrid in parallel directly in python and this has been implemented in the package. User just needs to provide sufficient computational resources!
