### ISSUE TITLE
Include `demo.ipynb` as part of the docs

### ISSUE THREAD

**Issue by navidcy** [COSIMA/regional-mom6#46]
@angus-g can you help me doing that? if you make a PR that just includes one of the notebooks as a docs page I can take it on from there. Don't bother about the content. I mostly need help with any extra dependencies the docs might need etc..

**Comment by angus-g** [comment]
Yeah, I can do that.

**Comment by navidcy** [comment]
Btw, the link to the notebook in the README is broken. But let's not bother fixing it, let's deal with this and then we can have the README pointing to the docs ;)
