### ISSUE TITLE
Local docs don't see the package itself?

### ISSUE THREAD

**Issue by navidcy** [COSIMA/regional-mom6#48]
So following the directions at https://regional-mom6.readthedocs.io/en/latest/contributing.html#documentation to build the docs locally the API website is empty.

Seems like the docs don't see the package itself? If I do `pip install ../.` then it works; but every time I edit a docstring I need to re-install? Somehow I'd expect (intuitively) that `sphinx` would be able to monitor changes in the package itself? Am I doing something wrong or that's how it is?

(Because the docs are not built via a Github Action I don't know exactly what's the pipeline for building them...)

cc @angus-g

**Comment by angus-g** [comment]
You need to do an editable install with `pip install -e .`, otherwise the installed version is essentially a snapshot of what was in the repo at the time you did install.

**Comment by navidcy** [comment]
Gotcha!
