### ISSUE TITLE
Docstring regarding the resolution in latitudinal directions is slightly ambiguous

### ISSUE THREAD

**Issue by navidcy** [COSIMA/regional-mom6#52]
This does not read right to me:

https://github.com/COSIMA/regional-mom6/blob/abf630d3fa909f0e609eaba167d454419f96e812/regional_mom6/regional_mom6.py#L509

`yextend` is a tuple with the extreme latitude values. But if these are symmetric about the equator then  `mean(yextent) = 0` and `res_y = 0`?

**Comment by ashjbarnes** [comment]
res_y is a modifier of latitude cell widths. At the equator this should be 1, since variations in lat and lon represent the same spatial extent. As you move to the poles you want this to decrease. I think what you're describing is the intended behaviour given that cos(0) = 1

**Comment by ashjbarnes** [comment]
What's the status of this issue? Is there a proposed change?

**Comment by navidcy** [comment]
I think I understand what `res_y` means to be and indeed it is also explained in the docstring.

However, my problem here perhaps points to the docstring which seems a bit contradictory.

https://github.com/COSIMA/regional-mom6/blob/d5326504c210cc328080e42028e3100e45066695/regional_mom6/regional_mom6.py#L521-L532

1. The `_make_hgrid` function as defined here doesn't seem to have a default behavior.
2. "This way, grids in the centre of the  domain are perfectly square" is wrong as they are not squares but rather spherical quadrilateral with equal Δlongitude and Δlatitude. Shall we rephrase?
3. 2. "latitude spaced with 0.1 cos(mean_latitude)" so that the grid cells at the center of the domain are squares... But that implies that the latitude grid is centered around the equator, right? What if the latitude domain is `[-80, -60]`. Then the center cell will have `Δlongitude = 0.1 deg` and `Δlatitude = 0.1 * cos(70degrees)` so they are not "squares".

**Comment by ashjbarnes** [comment]
Ohh true - that docstring is out of date! Good spotting. That would have been when _make_hgrid was using the rectangular hgrid function. I then modified it to be a wrapper for whatever grid gen scheme the user chooses (of which we currently have one). I think altering this docstring will fix this ambiguity

**Comment by navidcy** [comment]
Wanna give it a go?
