### ISSUE TITLE
Why is there a B-grid support?

### ISSUE THREAD

**Issue by navidcy** [COSIMA/regional-mom6#57]
I see some mention to MOM5 and B grid here:

https://github.com/COSIMA/regional-mom6/blob/663b5f3011475addb41abd3f1f619e39f4410a97/regional_mom6/regional_mom6.py#L576-L620

Is it to read an input from a B grid? From the code I understand that the initial condition is converted to a B grid but I don't understand why?

**Comment by ashjbarnes** [comment]
I was just trying to keep things as flexible as possible. The code is read as a B grid but output as C always right?

**Comment by navidcy** [comment]
Not sure if that's the case but I can see why that is the intention. Thanks for explaining. :)

**Comment by ashjbarnes** [comment]
Can you elaborate on this issue Navid? ACCESS-OM2 is a B grid, and this function is what does the interpretation of B grid data before it's converted to C grid for use with MOM6

**Comment by navidcy** [comment]
OK, so the B-grid support is for the input, right?

**Comment by ashjbarnes** [comment]
Yes only input. Output is always C

**Comment by navidcy** [comment]
Okie. I must have gotten the impression that it was for the output and I was confused. I'm closing this!
