### ISSUE TITLE
Convert demo that uses ACCESS-OM2 output to `cosima-recipes` example

### ISSUE THREAD

**Issue by navidcy** [COSIMA/regional-mom6#59]
At the moment there are two demos: one using GLORYS reanalysis and one using ACCESS-OM2 output.

Given that the ACCESS-OM2 output is not available to anyone outside Australia's HPC I suggest that at some point we move the ACCESS-OM2 demo into [cosima-recipes](https://github.com/COSIMA/cosima-recipes) (e.g. as part of https://github.com/COSIMA/cosima-recipes/pull/216?) and leave inside the package the demo that can be, in principle, executed by anyone.

We can always (and we should!) add a link to the cosima-recipes example in the package's docs.

**Comment by ashjbarnes** [comment]
I agree with this!

**Comment by navidcy** [comment]
I'm closing this since after #162 it's not related to this repo but it's left with cosima-recipes to deal with ;)

**Comment by navidcy** [comment]
> I'm closing this since after #162 it's not related to this repo but it's left with cosima-recipes to deal with ;)

@luweiyang, what I mean here is that #162 deleted this example from this repository and then https://github.com/COSIMA/cosima-recipes/pull/338 when merged, will move the ACCESS-OM2 example in the cosima-recipes repo
