### ISSUE TITLE
Set up scripts as a conda package

### ISSUE THREAD

**Issue by ashjbarnes** [COSIMA/regional-mom6#6]
This is one suggestion for usability. The notebook relies on three separate python files. One (regional_model_scripts) that was written by Angus and myself, and two that I've pinched from GFDL's repos and modified slightly. Perhaps it's easiest for users to import these scripts as needed from the cosima conda package, and then individual notebooks could live in a "MOM6 examples" folder somewhere separate from the source code

**Comment by ashjbarnes** [comment]
I'm now thinking that this can wait. Currently Cosima doesn't have a dedicated MOM6 examples page, so perhaps it makes more sense to keep everything together for now, and de-merge the tutorial from the scripts later when our code is more feature-complete, and there's a nice landing spot for out tutorial.

**Comment by angus-g** [comment]
https://github.com/COSIMA/cosima-recipes/issues/190 see here, I think MOM6-specific notebooks will come soon!

**Comment by navidcy** [comment]
#26 is a step towards this.

**Comment by navidcy** [comment]
I believe this is resolved, right?

**Comment by ashjbarnes** [comment]
Although still a work in progress, this has been done (thanks @angus-g !) and you can install this as a package. I'll close this issue, noting the more issues deal with the improvement of the packaging like #12

**Comment by navidcy** [comment]
Did we register the package with conda?
E.g., can you install it via

```python
conda install regional_mom6
```

**Comment by angus-g** [comment]
No. I think we'd either want to create a COSIMA [organisation](https://docs.anaconda.com/free/anacondaorg/user-guide/work-with-organizations/), and be able to install with something like `conda install -c cosima regional_mom6`, or get it accepted to [conda-forge](https://conda-forge.org/#add_recipe), which could be a bit more of a maintenance overhead.

**Comment by navidcy** [comment]
conda-forge would be nice :)
(when it's mature enough for that stage...)

**Comment by angus-g** [comment]
It might actually not be too hard, given the package can be installable as pure Python, with other dependencies (esmpy) in conda-forge already.

**Comment by angus-g** [comment]
https://github.com/conda-forge/staged-recipes/pull/24634

**Comment by ashjbarnes** [comment]
Very exciting!
