### ISSUE TITLE
Why there is `"conformal": "true"` flag?

### ISSUE THREAD

**Issue by navidcy** [COSIMA/regional-mom6#67]
What is this? There is no conformal mapping happening anywhere, right?

https://github.com/COSIMA/regional-mom6/blob/2f9d12b3c2beffefaae37d9a7c9c03c4dcc499f3/regional_mom6/regional_mom6.py#L368

**Comment by ashjbarnes** [comment]
I have no idea - I was just making the metadata match that of an existing example hgrid (probably from the EAC experiment) so that MOM6 would be happy

**Comment by navidcy** [comment]
Is MOM6 sad with `"conformal": "false"`?

**Comment by ashjbarnes** [comment]
Also no idea but if it's the configuration that works with existing MOM6 runs I don't see why we should change it by default. Maybe make it an option for users if we're worried it's inflexible?

**Comment by navidcy** [comment]
So when we create a MOM6 grid (any grid) it has this flag by default?

**Comment by ashjbarnes** [comment]
No, this won't apply to any grid just the current default which is the 'rectangular hgrid', when the "even_spacing" grid type flag is passed to the experiment class.

The grid generation component is completely modular. Like I've been saying about the 'rectangular hgrid', it just happens to be the grid that I'm using for my own research. As the project expands we/users should add other grids, or even better just call the[ mom6 grid generation tools](https://github.com/ESMG/gridtools). There's no need to make this particular grid generation function perfect and well rounded as it's just a placeholder for more a more comprehensive set of grid options in the future

**Comment by ashjbarnes** [comment]
I'll make a separate issue for the importing and integration of the grid generation tools into our module

**Comment by navidcy** [comment]
Sorry, I meant to say, if outside of `regional-mom6` we use MOM6 and create a grid, e.g., a rectilinear grid, then it has in its metadata `conformal: true`?

**Comment by ashjbarnes** [comment]
I think this is a question for the MOM6 forums. I've tried looking into it on both the FMS and MOM6 repos but it's pretty opaque about what this setting really does. It appears in the metadata of the regional setups that I've seen though

**Comment by ashjbarnes** [comment]
Can I close this issue @navidcy ?

**Comment by navidcy** [comment]
No. I'm not sure it's resolved. From what I understood we just "don't know". My question is whether this flag is true in MOM6 standard documentation. I presume it's not...

**Comment by navidcy** [comment]
Could you point me to where this flag originated? This "existing example" that you mentioned?

**Comment by ashjbarnes** [comment]
The flag appears in the `hgrid` files of other example mom6 regional configs (i.e the original EAC). When I wrote this code I was just automating the generation of a `hgrid` with identical metadata to the EAC experiment

It gets read by the 'FRE tools' when creating the mosaic, and then presumably also for the atmos-land-ocean mosaic tiles which depend on the `ocean_mosaic` (to my knowledge). 

https://github.com/NOAA-GFDL/FRE-NCtools/blob/8176c2b45079431f2053ec773253938f8aee4828/tools/transfer_to_mosaic_grid/transfer_to_mosaic.c#L420

**Comment by navidcy** [comment]
Does anybody from the MOM6 clan knows what this `"conformal": "true"` flag is for? May I ping @marshallward?

**Comment by marshallward** [comment]
I'm not sure this has much to do with MOM6.  It seems to be part of the FRE grid generation tools, and I suppose it ensures that any grid manipulations are conformal (angle-preserving).

From MOM6's perspective, a grid is a grid and it doesn't care how you made it, assuming it's not too perverse (e.g. curvilinear).  Grids from FRE-NCtools will provide some useful extra fields like `sin_rot`, but I believe MOM6 will compute many of those if they are missing.

If you want more info, I reckon the place to ask is to follow the link provided by @ashjbarnes and ask that group.  The top contributor, Miguel Zuniga, has recently departed, but Seth Underwood or Chris Blanton would be good people to start with.

**Comment by navidcy** [comment]
Thanks!

**Comment by navidcy** [comment]
I'm closing this for now.
