### ISSUE TITLE
Installation doesn't (appear to) correctly set up XESMF

### ISSUE THREAD

**Issue by ashjbarnes** [COSIMA/regional-mom6#72]
I'm building tests for the regridding side of the module and have run into an issue: the xesmf regridder terminates with

`ESMF_FileRegrid Library needed by ESMF not present - Internal subroutine call returned Error`

This is discussed [here](https://github.com/JiaweiZhuang/xESMF/issues/47)

To reproduce: Install as per instructions on readme and then type

`pytest -v --pyargs xesmf`

and the 'regridding' parts of xesmf will fail

I'll finish writing the tests on my local copy where the installation has been fixed manually, then have a go at fixing the installation but since this was done by @angus-g I might need a bit of help

**Comment by angus-g** [comment]
That's an outdated repository, it's moved to https://github.com/pangeo-data/xESMF now. Anyway, all the testing over there is done using mamba (and that's what I tend to use too), but I assume you're using Conda. It looks like they resolve the dependency tree slightly differently, and by default Conda will resolve the non-MPI versions of esmpy and esmf:
```
  esmf               conda-forge/linux-64::esmf-8.4.2-nompi_h9e768e6_3             
  esmpy              conda-forge/noarch::esmpy-8.4.2-pyhc1e730c_4
```

If you force `esmf>=8.4=mpi_mpich esmpy`, then it picks up a compatible version of esmf:
```
  esmf               conda-forge/linux-64::esmf-8.4.2-mpi_mpich_h2a0de38_103 
  esmpy              conda-forge/noarch::esmpy-8.4.2-pyhc1e730c_4
```

**Comment by ashjbarnes** [comment]
Great thanks Angus! So we should be able to add this line to our environment-ci.yaml file to fix? 

I've got a branch called `test-domain-generator` which is just meant to set up a new experiment and regrid a dummy bathymetry. It fails at the moment with a HDF error ([perhaps due to my local environment / HDF version? ](https://stackoverflow.com/questions/49317927/errno-101-netcdf-hdf-error-when-opening-netcdf-file)) and when I try and directly run the regridding step with 

`mpirun ESMF_Regrid -s bathy_original.nc -d topog_raw.nc -m bilinear --src_var elevation --dst_var elevation --netcdf4 --src_regional --dst_regional` I get required libraries issue. 

If you checkout to this branch, follow the regular 'testing environment' install instructions that Navid set out then hopefully this will reproduce my issues

**Comment by ashjbarnes** [comment]
Perhaps it's an issue with the testing environment? I'm going through your main installation instructions (in which esmpy is handled separately) and maybe that'll sort it out

**Comment by ashjbarnes** [comment]
Another update: doing the regridding directly with xesmf does seem to work with the default installation instructions. It's just when I'm trying to run `ESMF_Regrid` as a subprocess (either with our without mpirun) that it seems to run into errors.

For context: I'd switched to this technique for the bathymetry because `xesmf.Regridder` wasn't scalable for larger problems. Within a 28 core notebook environment I was able to easily sort out my Tasman domain with mpirun, whereas the Regridder failed.
