### ISSUE TITLE
Regridding bathymetry causing a crash

### ISSUE THREAD

**Issue by ChrisC28** [COSIMA/regional-mom6#78]
Hi all, 

I'm trying to create the inputs required to set up a high-ish resolution domain in the tropical pacific. However, regridding topography fails: 

`expt.bathymetry(
    '/g/data/ik11/inputs/GEBCO_2022/GEBCO_2022.nc',
    {"xh":"lon",
     "yh":"lat",
     "elevation":"elevation"}, ## Again this dictionary just maps mom6 variable names to what they are in your topog.
     minimum_layers = 1
    )`

With the error: 
`ValueError: Dimension 0 has 2 blocks, adjust_chunks specified with 1 blocks`

My domain limits are (in case it helps) are: 

`yextent = [-25,-10] ## latitude
xextent = [160,190] ## longitude `

Any advice? Is this a memory issue and I simply need to run on the large memory nodes?

**Comment by navidcy** [comment]
cc @ashjbarnes

**Comment by navidcy** [comment]
Which version of the package you using? Which commit? There has been a lot of changes lately. I'd urge you to use the latest.

**Comment by navidcy** [comment]
You are crossing 180? What happens if you stop at 179 out of curiosity?

**Comment by navidcy** [comment]
@ChrisC28 sorry I couldn't help out up to now. But if you let me know the commit of the package you use I'll try to reproduce the error and check it out.

**Comment by ashjbarnes** [comment]
Yeah I can't reproduce this error on the current version of the package over the same domain. Try using the latest version of this package and analysis3-unstable if you're on NCI to ensure that you're using the latest version of xESMF

**Comment by ChrisC28** [comment]
Hi all, 
Sorry, been a bit snowed under. @ashjbarnes could you let me know which version of xESMF you are using? I'll make sure that we are using the same version.

**Comment by ashjbarnes** [comment]
https://github.com/COSIMA/regional-mom6/blob/main/pyproject.toml lists all the requirements of version where there are any

So xESMF 0.8

**Comment by ashjbarnes** [comment]
Can confirm this was an issue with using an outdated version of the package.
